import { Project, Cluster } from './types';

export const mockProjects: Project[] = [
  {
    name: "pro-bi-com-us-jentadueto",
    department: "Human",
    cluster: ["BI4"],
    cost: "USD 2,890",
    percentage: "23.4%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
    owningAgency: "Boehringer Ingelheim Pharmaceuticals",
    projectUrl: "https://pro-bi-com-us-jentadueto.boehringer-ingelheim.com",
    repositoryUrl: "https://bitbucket.biscrum.com/wpsites/pro-bi-com-us-jentadueto",
    lagoonUrl: "https://lagoon.boehringer-ingelheim.com/projects/pro-bi-com-us-jentadueto",
    usage: {
      hits: 892345,
      hitsPct: 23.4
    },
    storage: {
      dbGb: 12.45,
      filesGb: 89.32,
      solrGb: 5.67,
      totalGb: 107.44,
      storagePct: 23.4
    },
    estimatedCost: "USD 2,890",
    monthTotalCost: "USD 12,390"
  },
  {
    name: "hz-qa-bi-hubnext-com",
    department: "Animal",
    cluster: ["BI5", "BI6"],
    cost: "USD 1,950",
    percentage: "15.7%",
    cms: "Custom",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
    owningAgency: "Boehringer Ingelheim Animal Health",
    projectUrl: "https://hz-qa-bi-hubnext-com.boehringer-ingelheim.com",
    repositoryUrl: "https://bitbucket.biscrum.com/wpsites/hz-qa-bi-hubnext-com",
    lagoonUrl: "https://lagoon.boehringer-ingelheim.com/projects/hz-qa-bi-hubnext-com",
    usage: {
      hits: 674123,
      hitsPct: 15.7
    },
    storage: {
      dbGb: 8.92,
      filesGb: 67.84,
      solrGb: 3.21,
      totalGb: 79.97,
      storagePct: 15.7
    },
    estimatedCost: "USD 1,950",
    monthTotalCost: "USD 12,390"
  },
  {
    name: "hz-storybook-bi-hubnext-com",
    department: "Human",
    cluster: ["BI3"],
    cost: "USD 1,750",
    percentage: "14.1%",
    cms: "WordPress",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
    owningAgency: "Boehringer Ingelheim Pharmaceuticals",
    projectUrl: "https://hz-storybook-bi-hubnext-com.boehringer-ingelheim.com",
    repositoryUrl: "https://bitbucket.biscrum.com/wpsites/hz-storybook-bi-hubnext-com",
    lagoonUrl: "https://lagoon.boehringer-ingelheim.com/projects/hz-storybook-bi-hubnext-com",
    usage: {
      hits: 534789,
      hitsPct: 14.1
    },
    storage: {
      dbGb: 7.23,
      filesGb: 45.67,
      solrGb: 2.89,
      totalGb: 55.79,
      storagePct: 14.1
    },
    estimatedCost: "USD 1,750",
    monthTotalCost: "USD 12,390"
  },
  {
    name: "centaura-se",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 1,420",
    percentage: "11.5%",
    cms: "Drupal",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "insights-in-ild",
    department: "Human",
    cluster: ["BI4", "BI5"],
    cost: "USD 980",
    percentage: "7.9%",
    cms: "GitBook",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "agentereversor-com-ar",
    department: "Animal",
    cluster: ["BI6"],
    cost: "USD 850",
    percentage: "6.9%",
    cms: "Custom",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "frontline-si",
    department: "Human",
    cluster: ["BI3", "BI4", "BI5"],
    cost: "USD 740",
    percentage: "6.0%",
    cms: "N/A",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "making-more-health",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 620",
    percentage: "5.0%",
    cms: "Salesforce",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "guides-boehringer-ingelheim-com",
    department: "Human",
    cluster: ["BI5"],
    cost: "USD 580",
    percentage: "4.7%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "bvdzero-es",
    department: "Animal",
    cluster: ["BI6", "BICN2"],
    cost: "USD 520",
    percentage: "4.2%",
    cms: "Custom",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  // Adding more projects to maintain the full dataset...
  {
    name: "vetmedica-research-platform",
    department: "Animal",
    cluster: ["BI4"],
    cost: "USD 890",
    percentage: "7.2%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "respiratory-solutions-hub",
    department: "Human",
    cluster: ["BI5"],
    cost: "USD 1,200",
    percentage: "9.7%",
    cms: "WordPress",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "diabetes-care-portal",
    department: "Human",
    cluster: ["BI3", "BI4"],
    cost: "USD 1,560",
    percentage: "12.6%",
    cms: "Custom",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "oncology-research-net",
    department: "Human",
    cluster: ["BI6"],
    cost: "USD 2,100",
    percentage: "17.0%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "animal-nutrition-guide",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 450",
    percentage: "3.6%",
    cms: "GitBook",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "immunology-insights",
    department: "Human",
    cluster: ["BI5", "BI6"],
    cost: "USD 1,340",
    percentage: "10.8%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "companion-animal-wellness",
    department: "Animal",
    cluster: ["BI3"],
    cost: "USD 760",
    percentage: "6.1%",
    cms: "WordPress",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "clinical-trials-dashboard",
    department: "Human",
    cluster: ["BI4", "BI5"],
    cost: "USD 1,890",
    percentage: "15.3%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "veterinary-diagnostic-tools",
    department: "Animal",
    cluster: ["BI6"],
    cost: "USD 680",
    percentage: "5.5%",
    cms: "Drupal",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "patient-support-program",
    department: "Human",
    cluster: ["BI3"],
    cost: "USD 920",
    percentage: "7.4%",
    cms: "Salesforce",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "livestock-health-monitor",
    department: "Animal",
    cluster: ["BICN2", "BI4"],
    cost: "USD 1,120",
    percentage: "9.0%",
    cms: "Custom",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "biosimilars-knowledge-base",
    department: "Human",
    cluster: ["BI5"],
    cost: "USD 640",
    percentage: "5.2%",
    cms: "GitBook",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "equine-care-solutions",
    department: "Animal",
    cluster: ["BI6"],
    cost: "USD 530",
    percentage: "4.3%",
    cms: "WordPress",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "rare-disease-registry",
    department: "Human",
    cluster: ["BI3", "BI6"],
    cost: "USD 1,650",
    percentage: "13.3%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "poultry-health-tracker",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 380",
    percentage: "3.1%",
    cms: "Custom",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "pharmaceutical-pipeline",
    department: "Human",
    cluster: ["BI4"],
    cost: "USD 2,450",
    percentage: "19.8%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "veterinary-education-hub",
    department: "Animal",
    cluster: ["BI5"],
    cost: "USD 710",
    percentage: "5.7%",
    cms: "WordPress",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "medical-affairs-portal",
    department: "Human",
    cluster: ["BI3", "BI5"],
    cost: "USD 1,280",
    percentage: "10.3%",
    cms: "Salesforce",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "swine-production-optimizer",
    department: "Animal",
    cluster: ["BI6", "BICN2"],
    cost: "USD 590",
    percentage: "4.8%",
    cms: "Drupal",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "therapeutic-area-insights",
    department: "Human",
    cluster: ["BI4"],
    cost: "USD 1,470",
    percentage: "11.9%",
    cms: "GitBook",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "companion-diagnostics",
    department: "Animal",
    cluster: ["BI3"],
    cost: "USD 820",
    percentage: "6.6%",
    cms: "Custom",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "regulatory-submission-tracker",
    department: "Human",
    cluster: ["BI5", "BI6"],
    cost: "USD 1,760",
    percentage: "14.2%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "farm-animal-welfare",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 440",
    percentage: "3.6%",
    cms: "WordPress",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "drug-safety-surveillance",
    department: "Human",
    cluster: ["BI3"],
    cost: "USD 1,390",
    percentage: "11.2%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "aquaculture-health-solutions",
    department: "Animal",
    cluster: ["BI4"],
    cost: "USD 660",
    percentage: "5.3%",
    cms: "Custom",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "personalized-medicine-platform",
    department: "Human",
    cluster: ["BI6"],
    cost: "USD 2,200",
    percentage: "17.8%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "veterinary-practice-management",
    department: "Animal",
    cluster: ["BI5"],
    cost: "USD 790",
    percentage: "6.4%",
    cms: "Salesforce",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "clinical-data-exchange",
    department: "Human",
    cluster: ["BI4", "BI5"],
    cost: "USD 1,630",
    percentage: "13.2%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "pet-health-monitoring",
    department: "Animal",
    cluster: ["BI3", "BI6"],
    cost: "USD 870",
    percentage: "7.0%",
    cms: "WordPress",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "biopharmaceutical-research",
    department: "Human",
    cluster: ["BICN2"],
    cost: "USD 1,540",
    percentage: "12.4%",
    cms: "GitBook",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "livestock-breeding-optimizer",
    department: "Animal",
    cluster: ["BI4"],
    cost: "USD 720",
    percentage: "5.8%",
    cms: "Drupal",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "therapeutic-protein-tracker",
    department: "Human",
    cluster: ["BI5"],
    cost: "USD 1,180",
    percentage: "9.5%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "animal-vaccine-registry",
    department: "Animal",
    cluster: ["BI6"],
    cost: "USD 610",
    percentage: "4.9%",
    cms: "WordPress",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "precision-dosing-calculator",
    department: "Human",
    cluster: ["BI3"],
    cost: "USD 960",
    percentage: "7.8%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "zoo-animal-care-system",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 420",
    percentage: "3.4%",
    cms: "Salesforce",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "molecular-diagnostics-hub",
    department: "Human",
    cluster: ["BI4", "BI6"],
    cost: "USD 1,820",
    percentage: "14.7%",
    cms: "Drupal",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "wildlife-health-tracker",
    department: "Animal",
    cluster: ["BI5"],
    cost: "USD 480",
    percentage: "3.9%",
    cms: "GitBook",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
  {
    name: "drug-interaction-checker",
    department: "Human",
    cluster: ["BI3", "BI4"],
    cost: "USD 1,100",
    percentage: "8.9%",
    cms: "Custom",
    stage: "Active",
    stageColor: "bg-green-100 text-green-800",
  },
  {
    name: "veterinary-telemedicine",
    department: "Animal",
    cluster: ["BI6"],
    cost: "USD 750",
    percentage: "6.1%",
    cms: "WordPress",
    stage: "In Review",
    stageColor: "bg-yellow-100 text-yellow-800",
  },
  {
    name: "biosecurity-monitoring",
    department: "Animal",
    cluster: ["BICN2"],
    cost: "USD 350",
    percentage: "2.8%",
    cms: "Custom",
    stage: "Legacy",
    stageColor: "bg-gray-100 text-gray-800",
  },
];

export const mockClusters: Cluster[] = [
  {
    id: "BI3",
    name: "BI3",
    type: "Production",
    status: "Operational",
    podDensity: 68.5,
    nodeCount: 15,
    ramUsage: 298.7,
    cpuUsage: 45.8,
    databaseSize: 2847.3,
    storageSize: 15789.2,
    hitsRequests: "2.8M",
    description: "Primary Production Cluster"
  },
  {
    id: "BI4", 
    name: "BI4",
    type: "Production",
    status: "Operational",
    podDensity: 78.2,
    nodeCount: 12,
    ramUsage: 256.4,
    cpuUsage: 15.4,
    databaseSize: 3241.7,
    storageSize: 18923.6,
    hitsRequests: "3.2M",
    description: "Production Cluster"
  },
  {
    id: "BI5",
    name: "BI5", 
    type: "Production",
    status: "Under Maintenance",
    podDensity: 65.1,
    nodeCount: 8,
    ramUsage: 189.3,
    cpuUsage: 82.4,
    databaseSize: 1892.8,
    storageSize: 12456.1,
    hitsRequests: "1.9M",
    description: "Production Cluster"
  },
  {
    id: "BI6",
    name: "BI6",
    type: "Production", 
    status: "Error",
    podDensity: 92.3,
    nodeCount: 4,
    ramUsage: 234.9,
    cpuUsage: 94.0,
    databaseSize: 4123.5,
    storageSize: 8734.2,
    hitsRequests: "4.1M",
    description: "Production Cluster"
  },
  {
    id: "BICN2",
    name: "BICN2",
    type: "Development",
    status: "Operational", 
    podDensity: 42.7,
    nodeCount: 6,
    ramUsage: 124.8,
    cpuUsage: 28.6,
    databaseSize: 892.4,
    storageSize: 5678.9,
    hitsRequests: "0.8M",
    description: "Development Cluster"
  }
];
